/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigationIdRouteImport } from './routes/investigation.$id'
import { Route as CompareId1Id2RouteImport } from './routes/compare.$id1.$id2'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationIdRoute = InvestigationIdRouteImport.update({
  id: '/investigation/$id',
  path: '/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareId1Id2Route = CompareId1Id2RouteImport.update({
  id: '/compare/$id1/$id2',
  path: '/compare/$id1/$id2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/compare/$id1/$id2': typeof CompareId1Id2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/compare/$id1/$id2': typeof CompareId1Id2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/compare/$id1/$id2': typeof CompareId1Id2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/methodology'
    | '/investigation/$id'
    | '/compare/$id1/$id2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/methodology'
    | '/investigation/$id'
    | '/compare/$id1/$id2'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/methodology'
    | '/investigation/$id'
    | '/compare/$id1/$id2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  MethodologyRoute: typeof MethodologyRoute
  InvestigationIdRoute: typeof InvestigationIdRoute
  CompareId1Id2Route: typeof CompareId1Id2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$id': {
      id: '/investigation/$id'
      path: '/investigation/$id'
      fullPath: '/investigation/$id'
      preLoaderRoute: typeof InvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id1/$id2': {
      id: '/compare/$id1/$id2'
      path: '/compare/$id1/$id2'
      fullPath: '/compare/$id1/$id2'
      preLoaderRoute: typeof CompareId1Id2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  MethodologyRoute: MethodologyRoute,
  InvestigationIdRoute: InvestigationIdRoute,
  CompareId1Id2Route: CompareId1Id2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
