import {
  FlaskConical,
  BookOpen,
  Lightbulb,
  TestTube2,
  ShieldCheck,
  FileText,
} from "lucide-react";
import { useReveal } from "@/lib/use-reveal";
import { METHODOLOGY_PHASES } from "@/lib/constants";
import { METHODOLOGY_ASCII } from "@/lib/ascii-patterns";
import { SectionHeader } from "./SectionHeader";

const ICON_MAP = {
  FlaskConical,
  BookOpen,
  Lightbulb,
  TestTubes: TestTube2,
  ShieldCheck,
  FileText,
} as const;

export function Methodology() {
  const revealRef = useReveal();

  return (
    <section id="methodology" className="relative py-24 px-4 lg:px-0 max-w-[1200px] mx-auto border-t border-border">
      <div className="ascii-bg">
        <pre>{METHODOLOGY_ASCII}</pre>
      </div>

      <div ref={revealRef} className="reveal-section">
        <SectionHeader title="Scientific Methodology" />

        <div className="overflow-x-auto pb-8 -mx-4 px-4 md:overflow-visible md:px-0 md:pb-0">
          <div className="flex items-center min-w-[900px] justify-between relative">
            <div className="absolute top-1/2 left-0 w-full h-px bg-border -z-10 translate-y-[-50%]" />

            {METHODOLOGY_PHASES.map((phase) => {
              const Icon = ICON_MAP[phase.icon];
              const isActive = "active" in phase && phase.active;

              return (
                <div key={phase.label} className="flex flex-col items-center gap-4 bg-background p-2 z-10">
                  <div
                    className={`w-16 h-16 rounded-sm border flex items-center justify-center transition-all duration-300 ${
                      isActive
                        ? "bg-surface border-primary animate-glow-pulse"
                        : "bg-surface border-border hover:border-muted-foreground"
                    }`}
                  >
                    <Icon
                      size={24}
                      className={isActive ? "text-primary" : "text-muted-foreground"}
                    />
                  </div>
                  <span className="font-mono text-[10px] uppercase text-muted-foreground text-center max-w-[100px] bg-background px-1">
                    {phase.label}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        <div className="mt-12 md:mt-16 max-w-2xl border-l-2 border-muted pl-6 ml-1">
          <p className="font-mono text-sm text-primary mb-2">THEORETICAL BASIS</p>
          <p className="text-base text-muted-foreground leading-relaxed">
            Grounded in Popper&apos;s falsifiability, Platt&apos;s strong inference, and
            Bayesian updating. Every hypothesis generated by Ehrlich carries explicit
            predictions, defined success criteria, failure criteria, and a prior confidence
            score before experimental validation.
          </p>
        </div>
      </div>
    </section>
  );
}
